### ISSUE TITLE
Incorrect project group.

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Arc#100]
The group specified here is com.github.anuken while the real group used by all of the arc modules is com.github.anuken.arc, i spent ages trying to figure out why thinks wouldn't work and it turns out it was this lmao
https://github.com/Anuken/Arc/blob/6fb037d33eed8af6a2e8d16cee147e8521215a8f/build.gradle#L26

**Comment by Anuken** [comment]
JITPack says to use that specific group:

![image](https://user-images.githubusercontent.com/10100000/155212207-0d71c954-63ab-40f4-b258-73ac05dfc303.png)

> real group used by all of the arc modules

What do you mean by "real group"? Why does it matter?

**Comment by Anuken** [comment]
Is this what you're confused about?

![image](https://user-images.githubusercontent.com/10100000/155212797-f090f763-ac96-4985-956f-4fb3c36b6231.png)

**Comment by buthed010203** [comment]
No, I made the game use a gradle [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) which doesn't like the name being different, I should be able to work around this by just using a custom configuration for the composition somehow

**Comment by Anuken** [comment]
Sounds like an issue with the build, not the project - I am using the correct group name as per JITPack docs, and I'd rather not change it without very good reason.

**Comment by buthed010203** [comment]
> Sounds like an issue with the build, not the project - I am using the correct group name as per JITPack docs, and I'd rather not change it without very good reason.

Fair enough, just a weird gradle thing that they node in the docs

**Comment by buthed010203** [comment]
> I should be able to work around this by just using a custom configuration for the composition somehow

I never was able to figure this out unfortunately.
