### ISSUE TITLE
Mindustry `Icon`s Ignore Being Resized

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Arc#106]
![image](https://user-images.githubusercontent.com/54301439/159425280-97ab4c18-55ea-4e0b-9004-c417bbc2e7d4.png)

My futile attempts to get the icon to resize:
![image](https://user-images.githubusercontent.com/54301439/159425429-eee27a53-f59e-4a32-af6c-7a376f0ff3c7.png)

(Using 2 because it's really small and would be easily visible in the case that it actually worked, which it didn't.)

**Comment by MEEPofFaith** [comment]
Solution: Set the button size in `defaults().size(#)`, then set the icons with `new TextureRegionDrawable(Icon.<whatever>)`

~~why does it have to be like this~~

**Comment by Anuken** [comment]
Those icons are special drawables that enforce specific size constraints, this is unrelated to Arc.

**Comment by MEEPofFaith** [comment]
I see
