### ISSUE TITLE
Defining custom colors for Arc.graphics.Color

### ISSUE THREAD

**Issue by Vortetty** [Anuken/Arc#11]
this may not be the right place to  put this because it also relates to mindustry.
Color.java defines basic colors, how would i make a custom one for the rhino js api in mindustry? i end up with errors setting Draw.color(0x00ffffff,0xffffff00,e.fin()); where colors are not how they should be.

**Comment by Anuken** [comment]
`new Color(r, g, b, a)` where `r, g, b, a` are values from 0 to 1.
