### ISSUE TITLE
IME edit don't clear composition when end composite.

### ISSUE THREAD

**Issue by way-zer** [Anuken/Arc#112]
1. Input
![image](https://user-images.githubusercontent.com/15688938/167283094-6daa69e3-baa1-4a7f-8806-c85aa509b5d3.png)
2. After composite
![Snipaste_2022-05-08_13-24-59](https://user-images.githubusercontent.com/15688938/167283090-35ae3415-e311-4545-912b-18c74614728f.png)
3. Then send out
![Snipaste_2022-05-08_13-26-26](https://user-images.githubusercontent.com/15688938/167283127-7b978c8b-6084-494f-8a90-03b248343e5b.png)

The composition should clear when step 2.

**Comment by Anuken** [comment]
I... don't entirely agree, it's part of the text field displayed text and still visible so it should stay there.

**Comment by way-zer** [comment]
> I... don't entirely agree, it's part of the text field displayed text and still visible on send so it should stay there.

`c's` is the `pingyin` of `测试`
After compositing `测试`, the `pingyin` should clear

**Comment by Anuken** [comment]
So what you're saying is, selecting a candidate does not replace the base candidate text? That seems like something that's Windows-specific or IME-specific, as I cannot reproduce it with a Japanese IME on Linux. You might have to look into the code responsible for this yourself.

![image](https://user-images.githubusercontent.com/10100000/167300969-b467ce5d-a489-4df9-abe3-0764d6b2225e.png)

**Comment by way-zer** [comment]
The candidate has been entered, but the candidate text don't clear.
I need to input a `space` or `backplace` to clear the candidate text.

**Comment by Anuken** [comment]
Right, but on my machine entering a candidate does clear the candidate text. It doesn't stay around.
