### ISSUE TITLE
Fi load order is seemingly random

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Arc#12]
My files:
```
Ainit.js
Bcommon.js
Cmech.js
Cunit.js
```

as per Mindustry's output, init, then mech, then unit, then common are loaded.
see https://github.com/DeltaNedas/entity-lib

**Comment by Anuken** [comment]
This has nothing to do with Fi. Java's file listing method doesn't guarantee any order, and neither do scripts.
