### ISSUE TITLE
architecture independence

### ISSUE THREAD

**Issue by tigercoding56** [Anuken/Arc#134]
Arm is not supported.

_Originally posted by @Anuken in https://github.com/Anuken/Arc/issues/127#issuecomment-1257108072_
      
this issue is here to suggest working on making the Arc engine   CPU architecture independent     which should be simple ( add if statements to remove x86 specific code on other architectures and maybe replace some things on compile (gradle build ) time )

**Comment by Anuken** [comment]
You have absolutely no clue what you are talking about.
