### ISSUE TITLE
FreeBSD errors

### ISSUE THREAD

**Issue by er2off** [Anuken/Arc#138]
- FreeBSD uses openjdk8 for devel/apache-ant, so to compile arc, need to compile natives, remove ant and compile other with newer openjdk (or manipulate with JAVA_HOME, oh hell)
- FreeBSD uses clang by default, but ant scripts uses gcc, so need to ln clang to gcc or install gcc as other package
- and as final, at the startup I have this error:
```
[I] [Core] Initialized SDL v2.26.3
ld-elf.so.1: /tmp/arc/2ff43028/libarc64.so: Undefined symbol "__wrap_memcpy"
```

**Comment by Er2ch** [comment]
After modifications in natives/memcpy_wrap.c it seems like stared but in endless loop (?), e.g. without any contents in SDL window
maybe Mindustry bug or long initialization

**Comment by Anuken** [comment]
See https://github.com/Anuken/Arc/pull/157#issuecomment-1812912375
