### ISSUE TITLE
[Feture Request] Use Keysym instead of Keycode. (Exotic Keyboard Layouts).

### ISSUE THREAD

**Issue by gegoxaren** [Anuken/Arc#14]
In SDL2 there is a field in the `struct SDL_Keysym` called `sym`, this field corresponds to the platform specific input of the keyboard, and is platform independent as the hard work is done in other part of the code.

http://hg.libsdl.org/SDL/file/78754c9488f6/include/SDL_keyboard.h#l47
http://hg.libsdl.org/SDL/file/78754c9488f6/include/SDL_keycode.h

https://wiki.libsdl.org/SDL_Keysym
https://wiki.libsdl.org/SDL_Keycode

This would solve https://github.com/Anuken/Mindustry/issues/1151

It would also solve other more exotic keyboard layouts like mine (Svorak).

Please have this in consideration. Thank you.

**Comment by Anuken** [comment]
Key symbols were used in an older version, and caused [significant problems](https://github.com/Anuken/Mindustry/issues/826). I don't see how switching to symbols will solve any issues with keyboard layout.
