### ISSUE TITLE
May deprecated `Seq.filter`?

### ISSUE THREAD

**Issue by way-zer** [Anuken/Arc#146]
This function is confusing. In many language, the `filter` don't modify itself.
And the kotlin has `Iterable<T>.filter` that is very confusing with the `Seq.filter`, this two has different effect.

For some usecauses, like `Vars.contents.blocks.filter()` will make game boom. While `Groups.player.filter` is very useful and safe to use.
## To deprecated
1. mark `Seq.filter` as deprecated.(no binrary breakchange)
2. use `Seq.removeAll` replace almost usecase.

**Comment by Anuken** [comment]
Was deprecated.
