### ISSUE TITLE
Wrong Parsing Unquoted strings in HJson

### ISSUE THREAD

**Issue by Zelaux** [Anuken/Arc#151]
I used [this](https://hjson.github.io/syntax.html) when writing HJson Support for Intellij idea
and I found some tricky cases which are parsed counterintuitively

Cases thats parsed in wrong way:
1. - Given HJson
    ```hjson
    it: it,
    value: value,
    ```
   - Expected Json
   ```json
   {"it": "it,", "value": "value,"}
   ```
   - Actual Json
   ```json
   {"it": "it", "value": "value"}
   ```
---
2. - Given HJson
    ```hjson
    [
    1, 2,
    O, T,
    3, 4,
    T, F
    ]
    ```
   - Expected Json
   ```json
   [1, 2, "O, T,", 3, 4, "T, F"]
   ```
   - Actual Json
   ```json
   [1,2,"O","T",3,4,"T","F"]
   ```

**Comment by Anuken** [comment]
This is not counterintuitive; why on earth would you expect the trailing comma to be part of the parsed string?! I intentionally made this change so modders wouldn't mess up when using unquoted strings. I don't care about the official spec - including commas (or, frankly, using unquoted strings at all) is a horrible idea.

**Comment by Zelaux** [comment]
I meant that the behavior described in the official spec is a little bit counterintuitive

**Comment by Anuken** [comment]
Right, but my parser doesn't have that behavior, so what is the issue with Arc...?

**Comment by Zelaux** [comment]
if you try to parse
```hjson
key: very, very, very, long value
```
You got pasing exeption.
And also if someone try to search information how to write on hjson, he will find [this](https://hjson.github.io)

**Comment by Anuken** [comment]
> key: very, very, very, long value

Why do this? I don't see why one would do that in a mindustry mod.

> And also if someone try to search information how to write on hjson, he will find [this](https://hjson.github.io/)

What's your point?

**Comment by Zelaux** [comment]
>Why do this? I don't see why one would do that in a mindustry mod.

Example
```
description: Yes, this is my first mod, but it will be wonderful!!!
```

> What's your point?

![image](https://github.com/Anuken/Arc/assets/58040045/794ab68a-6f0e-49ca-847a-7d059378dc10)

**Comment by Anuken** [comment]
> Example

![image](https://github.com/Anuken/Arc/assets/10100000/5d67b055-d070-420d-bfce-bada819255ec)

Result: `{"description":"Yes, this is my first mod, but it will be wonderful!!!"}`

> What's your point?

That's not a point, that's an image. What are you trying to say?

**Comment by Zelaux** [comment]
> Result: ....

I apologize in that case, further discussion is pointless
