### ISSUE TITLE
Broken Mat3D operations

### ISSUE THREAD

**Issue by Zelaux** [Anuken/Arc#153]
Method `arc.math.geom.Mat3D#mul(float[], float[])` works wrong when you pass `arc.math.geom.Mat3D#tmp` as `matb`
![image](https://github.com/Anuken/Arc/assets/58040045/638283b3-47ef-4e86-a547-03288954d186)
this happend for example in `arc.math.geom.Mat3D#scale(float, float, float)` method
![image](https://github.com/Anuken/Arc/assets/58040045/2c8b2760-630b-44d7-96c1-28ff3d0c8ca1)

**Comment by Zelaux** [comment]
What about rotate method?

**Comment by Anuken** [comment]
What about it?

**Comment by Zelaux** [comment]
I'm sorry, I didn't notice that everything was already fixed there too
