### ISSUE TITLE
What does boolf() even do?

### ISSUE THREAD

**Issue by TechFish3000** [Anuken/Arc#16]
I've seen it in the Examplemod javascript, but it has no documentation as far as I can see except in Arc. Also, I would talk via discord but it's blocked at my workplace.
Thanks in advance,
Techfish

**Comment by Anuken** [comment]
It creates an instance of a `arc.func.Boolf`, which is a functional interface that is equivalent to `Predicate` in Java and returns a boolean based on an input.
