### ISSUE TITLE
Could not resolve com.github.Anuken.Arc:flabel:v146.

### ISSUE THREAD

**Issue by shuo-liu16** [Anuken/Arc#175]
MindustryJavaModTemplate-master:main: Could not resolve com.github.Anuken.Arc:flabel:v146.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

-------------
When I use the mindustry template, an error is reported during the gradle build. What is the reason for this?
I would be grateful if you could help me

**Comment by Anuken** [comment]
This is unrelated to Arc's code - ask in the Discord for modding help. Make sure you're using [the latest version](https://github.com/Anuken/MindustryJavaModTemplate/blob/master/build.gradle) of the mod build script.
