### ISSUE TITLE
Adding VulkanAPI in Arc

### ISSUE THREAD

**Issue by Savin1play140** [Anuken/Arc#180]
It would be necessary to add supprot for VulkanAPI to Arc, since OpenGL works slower than the above mentioned API

**Comment by k8ieone** [comment]
@Savin1play140 Mindustry is a very lightweight game. I'm not sure if the performance improvements alone would be worth the development effort.

There is another aspect to this though. OpenGL is basically considered obsolete by most of the world and companies seem to be slowly dropping it in favor of Vulkan. At some point new devices will not support OpenGL at all.

**Comment by Savin1play140** [comment]
@k8ieone yes it is, but i add supprot VulkanAPI can get better results. And it can help with optimization. Adding this support will not hurt

**Comment by Anuken** [comment]
I have absolutely no interest in adding Vulkan support. 

> Adding this support will not hurt

You are vastly underestimating the amount of effort such a project would require.
