### ISSUE TITLE
Mods can't hook EventType.Trigger.update

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Arc#23]
Example code: `onEvent(Trigger.update, () => {})`
Throws `EvaluatorException: Can't find method mindustry.mod.Scripts.onEvent(mindustry.game.EventType$Trigger,function). (global.js#8)`

On BE 9171

**Comment by Anuken** [comment]
Not a bug, onEvent doesn't support triggers and doesn't really need to be around anymore. Use `Events.on`
