### ISSUE TITLE
Events.on(Trigger.update, Runnable) can't be used

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Arc#25]
Code:
```js
Events.on(Trigger.update, extend(java.lang.Runnable, {run() {
print("tick");
}}))
```

Error: `EvaluatorException: Can't find method arc.Events.on(mindustry.game.EventType$Trigger,adapter12)`

Tested on BE 8187

**Comment by Anuken** [comment]
`Events.run(Trigger.update, () => {})`

**Comment by DeltaNedas** [comment]
oh thats it
