### ISSUE TITLE
Ever considered swapping to JetBrains' annotations?

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Arc#48]
They have a few nice things such as properly telling you what could cause issues, also has a `@NotNull`
JetBrains `@Nullable`:
![](https://aethex.is-a.fail/8H4w0k.png)
Arc `@Nullable`:
![](https://mee6.is-terrible.com/hsSDqo.png)

**Comment by Anuken** [comment]
I don't want external dependencies or nasty long imports.

> `@NotNull`

Arc used to have this one, but it's redundant, because variables should be considered non-null by default.

**Comment by buthed010203** [comment]
Hmm how does one configure it to do so? I searched for an answer for a while and I remember it working like that ages ago but it hasnt for a while
